export const PROJECT_ID = import.meta.env.VITE_REACT_APP_APPWRITE_PROJECT_ID;
export const DATABASE_ID = import.meta.env.VITE_REACT_APP_APPWRITE_DATABASE_ID;
export const POSTS_COLLECTION_ID = import.meta.env.VITE_REACT_APP_APPWRITE_POSTS_COLLECTION_ID;
export const COMMENTS_COLLECTION_ID = import.meta.env
  .VITE_REACT_APP_APPWRITE_POSTS_COMMENTS_COLLECTION_ID;
export const BUCKET_ID = import.meta.env.VITE_REACT_APP_APPWRITE_BUCKET_ID;
export const APPWRITE_URL = import.meta.env.VITE_REACT_APP_APPWRITE_URL;